output/adcmesh.f90
output/asgsio.f90
output/stationProcessor.f90

fixed compilation issues associated with refactoring stationProcessor.f90 to handle multiple files.

fixed compilation issues associated with refactoring 

---

input/data_assimilation/offsetSurfaceGen.m

Gage data sanity checks for either completely or partially missing data.  Email to Jason with details:  
I've finished my edits, and it appears to be working.  I also made a number of smaller corrections in places where I saw bugs in the code.  Here's a laundry list in case I screwed something up due to misinterpretation:  
Near start, I moved the pathSep declaration so it didn't get cleared by the clearvars.  
Within the "if useDefaultStationList==false" statement, I've added some comments about changes made there to fix some variables, but it's under a condition I'm not able to test, and so cannot verify functionality.  
Near line 212, I changed "if exist('approxres','var')==0" to "==1"
Near line 558, within "if writeoutfil==1", I added the "nondefaultvals=..." line since a definition …

Added gage data sanity checks, did minor bug fixes

---

asgs_main.sh
platforms.sh

These changes will facilitate production on cloud computing resources as well as environments where MPI is not easily installed, such as Windows (especially under Cygwin).

merging serial branch to enable asgs to run adcirc and adcswan on a single processor

---

README-perlbrew.txt

Issue 90: Added information regrarding PERL5LIB in the ASGS
configuration file and how that might impact a perlbrew environment.

Added additional info to perlbrew how-to about PERL5LIB.

---

asgs_main.sh

Issue 101: Added a new variable option for the config file to set the base
directory for PREPPEDARCHIVE and HINDCASTARCHIVE. If RUNARCHIVEBASE is not
otherwise set in the configuration file, SCRATCHDIR is used. SCRATCHDIR also
now defaults to $SCRATCH (common envar on HPC systems) unless SCRATCHDIR is
explicitly defined in the asgs_main.sh configuration file (typically defined).

Default base directory of PREPPEDARCHIVE and HINDCASTARCHIVE to SCRATCH

---

CONTRIBUTING

Issue #147: Added instructions for contributors to follow for forking,
branching, and making pull requests. Basic information is there only,
future needs may require us to expand it.

Added preliminary document for contributors.

---

platforms.sh

Issue #155 : Copied over stampede2 section, made small changes;
added to env_disp function. Includes some minor additions from asgs-brew
work.

Added frontera to platforms.sh

---

cloud/general/init-adcirc.sh

named adcirc executables built by make and added SWAN=enable

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
cloud/general/t/netcdf4-bench.py
cloud/general/t/netcdf4-tutorial.py
cloud/general/t/verify-python-modules.py

Issue #194: Updated asgs-brew.pl to add environmental variables that
the setup.py script for netCDF4 needs. Added functional testing and
benchmarking Python scripts that will break if the module is not
properly aware of where to find netCDF4 or HDF5 libraries.

Fixed Python netCDF4 installation, added benchmark and verification

---

cloud/general/asgs-brew.pl

Issue #250: Perl doesn't support duplicate hash keys, so this was not
doing what was intended.
Also, testing out github "closing" syntax (should automatically link
issue with PR):
Resolves #250

Removed duplicate setting of PATH in asgs-brew.pl.

---

doc/monitoring/automated_monitoring.txt

Added documentation of command line utilities to check allocation

---

platforms.sh

Issue 311: Minor change that affects the URLs contained in emails
sent as notifications when ASGS posts to the THREDDS servers.
Resolves #311.

Updated HTTP port on which lsu_tds is listening.

---

cloud/general/DOT-asgs-brew.sh

Issue #301: Just moved it to what makes more sense semantically.
Resolve $301.

Moved 'purge statefile' to 'delete statefile'.

---

output/pullStationTimeSeries.f90

also added --zero-index command line option to write the station numbers starting from zero in the station output file.

Fixed bugs in pullStationTimeSeries related to reading an ascii fort.63 file

---

config/2020/asgs_config_NAC2014_nam_jgf.sh
config/mesh_defaults.sh

Added mesh_default.sh entry and config file to support NAC2014 mesh

---

config/2020/asgs_config_Shinnecock_nam_jgf.sh
config/mesh_defaults.sh
input/meshes/shinnecock/fort.26.shinnecock.template

For testing purposes; added config file to support running Shinnecock Inlet mesh on Frontera with NAM forcing (and SWAN coupling turned off). Resolves #335

Added config file and new entry in mesh_defaults.sh to support Shinnecock Inlet mesh

---

tides/tide_fac.f

Replaced arithmetic if statements with logical if statements.

---

asgs_main.sh

Issue #359: Removed what looked like a copy pasta error that may have
also been confusing the --defaultfile option that is available in the
get_flux.pl script.
Resolves #359.

Removed erroneous use of --defaultfile for control_file_gen.pl

---

cloud/Dockerfiles/Dockerfile.dev
cloud/Dockerfiles/Dockerfile.xenial
cloud/general/asgs-brew.pl
cloud/general/init-ffmpeg.sh
cloud/general/init-gnu-units.sh
cloud/general/init-gnuplot-noX11.sh
cloud/general/init-netcdf4.sh

Adds:
* `gnuplot` (nox)
* `ffmpeg`
* `units`
* updates Dockerfiles, make sure `zip` is installed on Ubunut (via Dockerfile)

Gnuplot etc

---

config/2021/asgs_config_Shinnecock_nam_jgf.sh
get_nam.pl
platforms.sh
util/input/meteorology/get_inv.pl

Resolves #404 by using 'guess platform' when the set_hpc() function comes back null due to the fully qualified domain name of a docker container coming back with an alphanumeric ID rather than a machine name.

Added initialization for asgs in docker container

---

output/nco_ncrcat.pl
output/thredds_download.sh

for creating various hindcast periods

Added scripts to automate the downloading of fort.61.nc files and concatenating them

---

get_nam.pl

removed statefile variable from script

---

archive/enstorm_pedir_removal.sh
asgs_main.sh
config/2021/asgs_config_Shinnecock_nam_subdomain_jgf.sh

Issue 419 re-established support for binary subdomain hotstart files

---

asgs_main.sh
config/2021/asgs_config_Shinnecock_nam_jgf.sh
config/forcing_defaults.sh
get_nam.pl

added capability to set forecastSelection=strict

---

archive/enstorm_pedir_removal.sh
asgs_main.sh
config/forcing_defaults.sh
control_file_gen.pl
get_nam.pl

resolves #425 ... I remembered to merge the latest master this time ... :-)

added new exit state to get_nam.pl : forecast-not-needed

---

asgs_main.sh

Do not merge yet, this is to illustrate changes and add documentation as a conversation piece at this point.

Added documentation to better describe structure of asgs_main.sh

---

storm_track_gen.pl

Updated to 2021 radii of uncertainty.

---

cloud/general/init-gnuplot-noX11.sh

Turned off the building of the interactive terminals qt, wxt, and cairo for gnuplot

---

cloud/Dockerfiles/Dockerfile.debian
cloud/Dockerfiles/Dockerfile.dev
cloud/Dockerfiles/Dockerfile.xenial

trivial: Added bc to the Dockerfiles to support monitoring

---

output/nco_ncrcat.pl

Updated script to enable usage with in-situ fort.61.nc files.

---

asgs_main.sh

Resolves #462 
I also updated the asgs wiki to reflect this.

Updated ASGSADMIN so it is set from .asgs_profile

---

asgs_main.sh
config/mesh_defaults.sh
control_file_gen.pl
input/meshes/common/swan/adcirc_swan_v52_fort.26.template
input/meshes/common/swan/adcirc_swan_v53_fort.26.template
input/meshes/common/swan/swaninit.template

Tested this successfully on the Shinnecock Inlet mesh. Resolves #1

added comment line length limiters for swan

---

asgs_main.sh

On queenbeeC. Resolves #450 
Not sure if this is the best approach, but seems the most contained and targeted. Please let me know what you think.

review but do not merge Modified job properties to use single queue for small parallel jobs

---

qscript.pl
qscript.template

Fixed run.properties for HPC nodes on PBS systems

---

PERL-MODULES
cloud/Dockerfiles/Dockerfile.dev
config/2021/asgs_config_HSOFS_nam_50s_jgf.sh
config/2021/asgs_config_OPENWATERv1e_al062018_subdomain_50s_jgf.sh
config/2021/asgs_config_OPENWATERv1e_nam_50s_jgf.sh

Resolves #477 but lacks significant integration with ourPerl, which will be required going forward.

installs dependencies required for running stations_check.pl and stations_to_kml.pl from natedill/ourPerl

---

asgs_main.sh
config/2021/ncfs-dev/ncfs-dev-ec95d_nam.sh
config/2021/ncfs-dev/ncfs-dev-hsofs_nam.sh
init-asgs.sh
monitoring/asgs-msgr.py
monitoring/asgs-msgr.sh
monitoring/logging.sh
monitoring/rp2json.py
output/transmit_rps.sh

Added ASGS pid to runprop message
Added new property called forcing.metclass with values of tropical|synoptic.

    New run.properties messaging for run properties database.

---

config/2021/ncfs-dev/ncfs-dev-ec95d_nam.sh
config/2021/ncfs-dev/ncfs-dev-hsofs_nam.sh
output/transmit_rps.sh

minor config updates for ncfs-dev
added missing pid to transmit_rps.sh
```
ppid=`ps -o ppid $$ | sed '1d'|  sed -r 's/^ *//g'`
ppid=`ps -o ppid $ppid | sed '1d'|  sed -r 's/^ *//g'`
```

small fix for transmit_rps.sh; config updates for ncfs-dev

---

bin/verify
platforms.sh

Added chg-1.oden.tacc.texas.edu as 'tacc_tds2'.

---

asgs_main.sh

Added concatenation of tc forecast properties to run.properties file.

---

asgs_main.sh

Fixed typo in path to notification scripts.

---

output/adcmesh.f90
output/addMeshToNetCDF.f90
output/asgsio.f90
output/generateXDMF.f90
output/logging.f90
output/makefile

Added support for visualizing hotstart files including those generated by adcirpolate

---

asgs_main.sh
config/2021/asgs_config_NAC2014_nam_jgf.sh
platforms.sh

Changed default serial queue from normal to small on Frontera.

---

asgs_main.sh

Removed echohelp function; it is no longer needed.

---

patches/ADCIRC/v53release-adcircpolate/04-issue-551.patch
patches/ADCIRC/v53release-testsuite/03-netcdfhome-cleanup.patch
patches/ADCIRC/v53release-testsuite/04-issue-551.patch
patches/ADCIRC/v53release/03-issue-551.patch

Issue 551: Apply v53release based diff to related patch sets.
Note: v55release or v55.00 based patch sets are not covered in this
PR.
Resolves #551.

Added diff from Issue-551 into v53 based patch sets.

---

config/mesh_defaults.sh

Updated mesh defaults for LAv21a to recycle LAv20a

---

asgs_main.sh

Set new ADVISORY num before writing forcing.nwp.year property

---

asgs_main.sh
platforms.sh
qscript.pl

Abstracting hint for PPN for serial jobs on queenbee, supermic.

---

config/2021/asgs_config_HSOFS_nam_jgf.sh
config/2021/asgs_config_LAv21a_nam_jgf_23kcms.sh
config/2021/asgs_config_PRVI15_nam_jgf.sh
config/2021/asgs_config_SABv20a_nam_jgf.sh
output/opendap_post.sh

added graceful handling of OPENDAPNOTIFY set to null or an empty string

---

output/nco_ncrcat.pl

Removed advisory directories with .old extension from list of directories to be used in validation

---

control_file_gen.pl

Added run duration in hours to the RUNID line in the fort.15

---

asgs_main.sh
config/2021/asgs_config_EC95d_al162021_jgf_bnowcast.sh
config/2021/asgs_config_EC95d_al182021_jgf_bnowcast.sh
config/2021/asgs_config_PRVI15_al182021_jgf_bnowcast.sh
control_file_gen.pl
storm_track_gen.pl

Improvements to download NAM files for tc-forced nowcasts.

---

control_file_gen.pl

Added more complete run id line for fort.15.

---

output/station_transpose.pl

This ended up being easier than I thought.

Updated coldstartdate property key.

---

monitoring/captureJobID.sh

Added code to capture job ID to jobs.status on QueenbeeC.

---

control_file_gen.pl

extended default output end time to 9999.0 days

---

platforms.sh

Update port for RENCI thredd server from 8080 to 80.

---

asgs_main.sh

resolves #762 
I am testing this now on QBC.

Based date math for NAM data on UTC timezone

---

cloud/general/DOT-asgs-brew.sh
cloud/general/init-replaycli.sh

Issue 758: First delivery of replaycli/StormReplay.com service.
Resolves #758.

Added optional install for replaycli.

---

bin/verify
cloud/general/DOT-asgs-brew.sh

Issue 768: Updating minor things while creating ASGS Quick
Reference 1.7.
Resolves #768.

Updated menu, verify command reference to python -> python3.

---

bin/get_nam_status.pl
bin/latest.pl

Issue 770: Wrapped $ftp->ls() in an eval {} and now outputs a meaningful
message; also exits script with an error code of 1. All $ftp calls in
this script were wrapped with eval {}, all "die"s were changed to "exit
1" in order to keep the logs cleaner. Explicitly set Timeout => 120
(seconds), which is the default - just to make it more clear.
Resolves #770.

Catch exception thrown when Net::FTP timesout during `ls`.

---

config/mesh_defaults.sh

added number of nodes and elements to mesh_defaults.sh file

---

asgs_main.sh

Resolves #265 ; Captures exit code of the `control_file_gen.pl` script as well as missing or zero length fort.15 (and fort.26 if `WAVES=on`). Improves logging of these conditions.
These changes have not been tested yet, @wwlwpd please have a look to see if my approach is sound.

Improved checking status of control_file_gen.pl, fort.15 and fort.26

---

.gitignore
PERL-MODULES
PERL-MODULES.notest
asgs_main.sh
bin/guess
bin/show
cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
cloud/general/init-perlbrew.sh
init-asgs.sh
makefile
platforms.sh
platforms/README
platforms/penguin/about.txt
platforms/penguin/init.sh

Issue 790: Creating a more extensible "system" for adding
new platforms. System also makes it easier for sites to maintain
their own set of supported platforms outside of this repo.
As a test, support for a Penguin Computing system was added.
Resolves #790.

Adding system, extending platform support.

---

PERL-MODULES
bin/asgs-lint

Added a ASGS config "linter", as part of a preflight check.

---

PERL/ASGSUtil.pm
asgs_main.sh
bin/get_nam_data.pl
bin/get_nam_status.pl
bin/select_nam_nowcast.pl
downloadBackgroundMet.sh
monitoring/logging.sh

light refactoring to support checks on exit codes and logging for data download scripts 

---

bin/asgs-sendmail
init-asgs.sh
output/TRACKING_FILES/particle_tracking_email.sh
output/best_post.sh
output/blanton_cyclone_notify.sh
output/cera_notify.sh
output/notify.sh
output/opendap_post.sh
output/opendap_post2.sh
output/post.sh
output/scp_only.sh
platforms.sh
platforms/penguin/init.sh
variables_init.sh

* moved $SCRIPTDIR/asgs-sendmail.pl -> $SCRIPTDIR/bin/asgs-sendmail (so it's in `asgsh`'s `$PATH`)
* updated all places in repo that used it, except one place that was attaching files
* NOTE: some places were still using the system `mail` utility, which was unexpected (my fault)

invasive correction for mail integration

---

storm_track_gen.pl

Update radii of uncertainty to 2022 values

---

asgs_main.sh

Adding `HINDCASTONCE_AND_EXIT` for running hindcast once, then exiting.

---

asgs_main.sh

Removed erroneous check for the existence of the fort.26 file

---

patches/ADCIRC/v55.01-5bc04d6/01-v55release-qbc.patch
patches/ADCIRC/v55.01-5bc04d6/02-v55release-netcdfhome-cleanup.patch
patches/ADCIRC/v55.01-5bc04d6/03-issue-559.patch
patches/ADCIRC/v55.01-5bc04d6/04-issue-743-rostam.patch
patches/ADCIRC/v55.01-5bc04d6/05-issue-820-lonestar6.patch
patches/ADCIRC/v55.01-5bc04d6/06-issue-820-lonestar6-2.patch
patches/ADCIRC/v55.01-5bc04d6/about.txt
patches/ADCIRC/v55.01-5bc04d6/info.sh

Adding ADCIRC patchset for SHA 5bc04d6.

---

asgs_main.sh

Fixed test for single digit storm number.

---

asgs_main.sh

Added --nscreen that seemed to be missing.

---

cloud/general/DOT-asgs-brew.sh

Removed resetting SCRIPTDIR to pwd

---

monitoring/captureJobID.sh

Added ls6 to list of tacc machines that need to filter output from sbatch for jobID

---

downloadGFS.sh

Allowed grib2 files to be reported as type 'data' from bash file command

---

downloadGFS.sh

Added checks for data file type for grib2 on forecast

---

patches/ADCIRC/v53release-gfortran-desktop/01-v53release-qbc.patch
patches/ADCIRC/v53release-gfortran-desktop/02-netcdfhome-cleanup.patch
patches/ADCIRC/v53release-gfortran-desktop/03-issue-551.patch
patches/ADCIRC/v53release-gfortran-desktop/04-issue-549.patch
patches/ADCIRC/v53release-gfortran-desktop/05-issue-550.patch
patches/ADCIRC/v53release-gfortran-desktop/06-issue-743-rostam.patch
patches/ADCIRC/v53release-gfortran-desktop/07-issue-820-lonestar6.patch
patches/ADCIRC/v53release-gfortran-desktop/08-issue-820-lonestar6-2.patch
patches/ADCIRC/v53release-gfortran-desktop/09-issue-840-supermike-iii.patch
patches/ADCIRC/v53release-gfortran-desktop/10-issue-819-gfortran-desktop.patch
patches/ADCIRC/v53release-gfortran-desktop/about.txt
patches/ADCIRC/v53release-gfortran-desktop/info.sh

Fixed v53 gfortran desktop build with one new patch to cmplrflags.mk

---

output/includeWind10m.sh

resolves #940 ; testing this now

critical path fix for copying Wind10m layers rather than using ln -s

---

init-asgs.sh

added export of WORK and SCRATCH from init-asgs.sh to update-asgs

---

archive/enstorm_pedir_removal.sh
monitoring/captureJobID.sh

resolves #982 resolves #983
tested successfully on mike

fixed jobs.status on mike and fixed `rmpurge` on platforms that require it

---

asgs_main.sh
config/io_defaults.sh
control_file_gen.pl

adds support for netcdf3 hotstart files

---

control_file_gen.pl
input/meshes/common/swan/adcirc_swan_v52_fort.26.template
input/meshes/common/swan/adcirc_swan_v53_fort.26.template

correct swan fort.26 comment lines that were too long

---

writeProperties.sh

Updated run.properties to reflect blended winds.

---

output/adcmesh.f90
output/generateCPP.f90

resolves #1059 ; I've tested this and confirmed that it works as expected

Added support for unit sphere coords

---

config/forcing_defaults.sh

migrate to GFS url 16.3

---

cloud/general/init-ffmpeg.sh

Added check for downloading nasm

---

output/adcmesh.f90
output/pullStationTimeSeries.f90
output/resultScope.f90

Improvements to station handling

---

storm_track_gen.pl

Updated cone for 2023 NHC statistics

---

output/adc2vtk.pl

resolves #1163 and resolves #1170 ... tested successfully

Write levee boundaries in ArcMap CSV XYZ format and opt in to 2DM format

---

config/mesh_defaults.sh
input/meshes/CPRA23/combined_stations_20230824.txt

Updated stations file for 17thStCanal location.

---

init-asgs.sh
platforms/chpc/README
platforms/chpc/about.txt
platforms/chpc/init.sh

@jasonfleming I need to get Javier attached to this also so we can test. 
...
Issue 1202: This commit will make CHPC a default option when running the ./init-asgs.sh installation wizard for ASGS.
Resolves #1202.

Adding support for Bama's CHPC Cluster.

---

output/adc2vtk.pl

Also writes other helpful pieces of information. Resolves #1206

Added code to write boundary types to `.vtp` files

---

output/generateXDMF.f90

resolves #1052 ... tested and confirmed that this works. Ready to merge from that perspective.

Added vector magnitude attribute to xmf

---

asgs_main.sh
config/forcing_defaults.sh
get_atcf.pl
storm_track_gen.pl

Added `TRIGGER=auto` as a config option for vortex model hindcasts to eliminate a need to generate mock xml forecasts

---

output/asgsio.f90
output/generateXDMF.f90

resolves #1256 resolves #1169 resolves #1053 resolves #1020

Fixing XDMF variable naming issues and removing vector magnitude

---

config/mesh_defaults.sh
control_file_gen.pl
platforms.sh

Added support for empty list of nodal attributes for fort.15

---

asgs_main.sh

Fixed typo NDSET->NWSET

---

asgs_main.sh
manageHooks.sh
monitoring/logging.sh
output/opendap_post2.sh
platforms.sh

Removed centralized scenario logging

---

asgs_main.sh
monitoring/captureJobID.sh
platforms.sh
qscript.pl

resolves #1306 with additional testing now

Fixed ppn hint and jobID capture on mike

---

config/mesh_defaults.sh

resolves #1304 and tested successfully

Changes to support the CPRA23v05b mesh

---

PERL/ASGSUtil.pm
bin/asgs-mon
etc/asgs-mon-plugins/000-asgs_main-pid-check
etc/asgs-mon-plugins/001-instance-status-check
etc/asgs-mon-plugins/002-hook-status-check
etc/asgs-mon-plugins/003-syslog-progress
etc/asgs-mon-plugins/004-instance-status-progress
etc/asgs-mon-plugins/005-hook-status-progress
etc/asgs-mon-plugins/006-rundir-du
etc/asgs-mon-plugins/007-failed-dir
etc/asgs-mon-plugins/008-heart-beat
etc/asgs-mon-plugins/999-critical-test
etc/asgs-mon-plugins/999-notify-test
etc/asgs-mon-plugins/999-warning-test
etc/asgs-mon-plugins/README
etc/asgs-mon-plugins/_bash-helper-functions.sh

and so it begins...
Build out basic checks to call it done (partial list?):

Issue 1219 asgs-mon

---

bin/asgs-lint

Added support for GFS, gfsBlend, and gfsforecast in scenario package

---

bin/sq
platforms/stampede3/init.sh

Minor changes needed to run on Stampede3 operationally.

---

config/io_defaults.sh
monitoring/logging.sh
output/opendap_post2.sh

Added code to maintain precedence of `OPENDAPNOTIFY` from `run.properties` file

---

qscript.template

resolves #1340 (padcirc not padcswan)

Fixed executable to be used for Wind10m scenarios 

---

config/mesh_defaults.sh

Corrected setting of GRIDFILE

---

asgs_main.sh

Fix calculation of vortex forecast end time 

---

cloud/general/DOT-asgs-brew.sh

`clone profile` no longer modifies parent profile (ASGS_CONFIG)

---

input/meshes/common/swan/adcirc_swan_v53_parameters_fort.26.template
qscript.template
util/output/quality.sh

resolves #1345 ... testing now

Added quality checks to queue script template

---

output/adc2vtk.pl
output/adcmesh.f90
output/checkAdcircMesh.f90

tested successfully, resolves #1359

Added code to support edge length calculation and visualization

---

util/input/nodalattr/convertna.f90
util/input/nodalattr/submergence_eddyvis.f90

Fixed build issues with edge length calculation

---

init-asgs.sh

Needed a deeper check for adcirclive/etc.

---

bin/repost-all
patches/ADCIRC/v56.0.0-beta.2/01-cmplrflags-mk.patch

Emergency update to v56 beta 2 patch for Frontera.

---

patches/ADCIRC/v53release/01-cmplrflags-mk.patch
patches/ADCIRC/v53release/02-prep-F.patch

Updating patchset, reapplying a lost fix to prep/prep.F

---

patches/ADCIRC/v56.0.2/01-cmplrflags-mk.patch

Added "rhel" support for Intel OneAPI for ADCIRC v56.0.2

---

asgs_main.sh
storm_track_gen.pl

Moved writing of BEST track properties to earlier in the script

---

config/forcing_defaults.sh
downloadGFS.sh

resolves #994; I am testing this now

Increasing GFS regridding resolution to 0.1 degree

---

config/mesh_defaults.sh

resolves #1430 ; I have tested this and confirmed that it works.

Modified default wind drag limit for NGOMv19b

---

bin/fetch
cloud/general/DOT-asgs-brew.sh

Added repo to `fetch cera`

---

config/mesh_defaults.sh
input/meshes/EGOMv20b/EGOMv20b.15.ASGS2024.1.template

Modified default parameter package

---

config/mesh_defaults.sh

Fixed typo in EGOMv20b setting

---

config/mesh_defaults.sh
input/meshes/SABv20a/SABv20a.15.ASGS2024.1.template

Updated parameters for SABv20a mesh

---

storm_track_gen.pl

Updated uncertainty radii for 2025

---

asgs_main.sh

Loosened check on comparison of RunStartTime and RunEndTIme

---

config/mesh_defaults.sh
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_10kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_11kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_12kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_13kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_14kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_15kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_18kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_5kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_6kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_7kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_8kcms.txt
input/meshes/NGOMv19b/NGOM_RT_v19b_river_flux_9kcms.txt

Updated settings for NGOMv19b

---

output/asgsio.f90

Fixed writing of `ESLNodes.63` data to netCDF

---

input/meshes/SABv20a/SABv20a.15.ASGS2024.1.template

Removing line from SABv20a.

---

input/meshes/CPRA23/CPRA23.15.ASGS2024.1.template
input/meshes/CPRA24/CPRA24.15.ASGS2024.1.template
input/meshes/EGOMv20b/EGOMv20b.15.ASGS2024.1.template
input/meshes/LAERDC/LAERDCv5k.15.ASGS2024.1.template
input/meshes/LA_v20a/LA_v20a-WithUpperAtch.15.ASGS2024.1.template
input/meshes/NGOMv19b/NGOMv19.15.ASGS2024.1.template
input/meshes/TXLA22a/TXLA22a.15.ASGS2024.1.template
input/meshes/hsofs/hsofs-parameters.15.template
input/meshes/naccs/NAC2014.15.ASGS2024.1.template
input/meshes/nc_v6b/NCv6d_2024.fort.15.template
input/meshes/nc_v9.99_w_rivers/NCv999_2024.1.fort.15.template
input/meshes/shinnecock/shinnecock-parameters.fort.15.template

Removed placeholder for dynamic water level correction namelist

---

PERL-MODULES
PERL-MODULES.notest

Issue 1500: test suite was probably causing the firewall to trigger on QBD, maybe others.
Resolves #1500.

Moved IO::Socket::SSL to PERL-MODULES.notest

---

ssh-servers/seahorse1_tds.sh

resolves #1560 ; tested successfully with status files

Added ssh server on DigitalOcean

---

input/meshes/TXLA22a/init.sh

Corrected typo in `init.sh` for TXLA22a
