StormSurgeLive/asgs

output/stationProcessor.f90

Two warning messages wrote out values in the wrong order, making the messages incorrect and confusing.  Note also there's an errant comma in the 2nd write command that was updated.  I don't understand why it's there, but am not touching it.

Fixed warning messages

---

PERL/README-perlbrew-patch.txt
PERL/patchperl.patch

The root issue is that Lustre treats a write to a write protected
file as fatal and kills the entire process.

Added patch and README for fixing perlbrew on Stampede2

---

PERL-MODULES
README-perlbrew.txt
README-setup-email.txt
asgs-global.conf.sample
asgs-sendmail.pl
output/emailattach.py

Issue-95: Added a commandline tool for email integration with AWS
SES via SMTP. Credentials and set up are required, as are additional
Perl modules. The perlbrew README was updated, list of modules updated,
and a README for setting up email was added.

Added AWS integration tool for sending email via SES.

---

README-perlbrew.txt

No issue: This is just a README update to clarify that it is preferable
to added the perlbrew source line to ~/.bash_profile in most cases.

Updated perlbrew information regarding user environment.

---

asgs-brew.pl
cloud/general/init-openmpi.sh
install/install-hdf5-netcdf4.sh
makefile
output/cpra_postproc/makefile
output/makefile

Issue 107: Built an extensible Perl script to manage the building
of an entire ASGS environment locally. Currently the steps in the
script focus on the building of NetCDF, HDF5, and any Fortran
utilities in the ASGS repository that have a makefile associated
with them. Extending this script to handle most, if not all of the
tasks associated with building a working ASGS environment from
scratch on any platform should be broken out into future Issues.
The groundwork has been laid with this script. A basic unit test
was created, but it's not sufficient to exercise the script. Some
changes were made to existing makefiles and scripts that are used
to do the tedious work associate with building and compiling.

Created a Perl script to manage building all Fortran utilities.

---

asgs-sendmail.pl

Issue 133: This change allows the --to option to utilize a list of
email addresses that are delimited by either spaces or commas. Since
this script is meant to be mostly a drop in replacement for sendmail,
it and sendmail delimits email addresses by spaces, it's important
to support this.

--to accepts comma or space delimited email address lists now

---

cloud/general/asgs-brew.pl

Issue #171: some of the steps in asgs-brew.pl had references to
$HOME and broke when trying to install it into alternative locations.
This fix removes the fragility and should allow ASGS to be installed
anywhere, to anywhere. Access to a $USER's true $HOME is needed for
Perl, Python, and asgsh; since these 3 components are meant to serve
all of an operators installations globally.

Fixed relocatability bug in asgs-brew.pl

---

init-asgs.sh

Issue #199: Checking for $HOME/asgs and running 'git clone' to
download the current ASGS repository was an artifact from earlier
development and should not have been there. Removed this check. Also
added header information regarding the license for this script.

Removed immediate "git clone" of asgs repository in init-asgs.sh.

---

init-asgs.sh

Issue #200: Added warning when asking for installdir; defaults to
$WORK/opt if $WORK is set; otherwise defaults to $HOME. Updated
command string for asgs-brew.pl to set profile name (actual bug
found when working original purpose of this issue).

Added warning about no shell expansion in init-asgs.sh

---

Dockerfile
Dockerfile.git-master
cloud/general/init-perl-modules.sh

Issue #165: Adding a Dockerfile to support the evaluation,
exploration, and local use of the 2019stable release of ASGS.
The Dockerfile is used by a developer or maintainer when after
a release when they wish to make a Docker image of the environment
available at https://hub.docker.com.
This change also includes a minor change to the script that installs
the Perl modules because during the development of the Dockerfile,
it was discovered that the upstream version of Date::Handler had some
failing tests that were preventing the module from being installed.
This was through no fault of ASGS, nor does it appear that this test
failing affects ASGS in any negative way.

Adding initial Dockerfile

---

cloud/replay-server/Dockerfile
cloud/replay-server/README
cloud/replay-server/run-vsftpd.sh
cloud/replay-server/start-ftp.sh
cloud/replay-server/start-www.sh
cloud/replay-server/vsftpd.conf

Issue #214: The idea is to maintain a replay server for most to use,
but these files will help one get started if they wish to run their
very own replay services. This provides set up for anonymous FTP using
vsftpd and a web server for RSS using the stock nginx Docker container
at Docker Hub.

Adding Dockerfile and scripts used for storm replay infrastructure.

---

input/sample_advisories/ftp_rotate.sh
input/sample_advisories/replay-storm.ini
input/sample_advisories/replay-storm.pl
input/sample_advisories/replay-storm.tpl

Issue #215: This is the initial script for replaying storms
in a configurable way for testing, development, training,
conducting readiness drills. There are lots of opportunities
to determine how to extend this script. It is meant to run on
a server that is configured with FTP and RSS (via http) which
mimicks how the NHC provides advisories during actual events.
Documentation for the script is provided via POD and can be
viewed using "perldoc ./replay-storm.pl".
In this first version, index-at.xml files are updated for each
storm by adding an entry for each storm. Storms are updated in
place, but the existing scheme allows each storm among many to
exist the XML exactly one time.

Added inital tool for easily replaying storms.

---

cloud/general/t/verify-perl-modules.t

Issue #184: Access to AdcGrid is implicitly proved during the
`perl -c` check, but adding it to the Perl module verification
check so there is no doubt.

Added AdcGrid to the Perl module check available in asgsh.

---

get_atcf.pl
input/advisoryMonitor.sh

Issue 209: Added code to fallback to http (non-ssl) when there is
a 599 HTTP response code, indicating in this case that the connection
to port 443 (https) was refused. Cleaned up a few things while in
there; the first 4 commandline arguments are preserved, but added
a few more to allow for specifying FTP hostname/ip, RSS hostname/ip,
trigger type, etc. Any other cleaning up preserved the existing
functionality.
This was mainly done to make it easier to test ad hoc FTP and WWW
servers that might be set up to mimic the NHC infrastructure, thus
providing another and more realistic way to do integration testing
(and real investigation/research).

Allow advisoryMonitor.sh to fallback to http (non-ssl) for testing.

---

qscript.pl

Issue #239: Updated regex that extracts hour:minutes:seconds from
the *WALLTIME passed via --walltime option so that it can handle
single digit hours (and minutes and seconds).
Now accepts:
* 02:00:00
* 2:00:00
* 10:00:00
* etc
Fixes Issue #239.

Modified qscript.pl to handle single digit hour *WALLTIMEs.

---

platforms.sh

Issue #241: When starting asgsh, platforms.sh file has a case
statement in it for Hatteras that was issuing a warning if the
current user was not accounted for; removed this warning and moved
module includes inside of the specific users. Set default modules
to include for unspecified users to what seemed same - specifying
the Intel compiler suite and OpenMPI module.
For the existing users on Hatteras accounted for in this way,
care was taken to ensure the effective environment that was being
configured remained the same as before this change.
Auto-close link: Resolves Issue #241.

Avoid spurious module warnings on Hatteras when starting asgsh.

---

cloud/general/DOT-asgs-brew.sh
cloud/general/README.asgsh
cloud/general/asgs-brew.pl

Issue #244: This issue was discovered when implementing commandline
flag processing to the asgsh shell command that starts the ASGS
Shell Environment. 'set' is a built-in keyword of bash and asgsh
was using it for other purposes.  The new command is 'define' and
works exactly the same as 'set' did. The documentation included
with asgsh was also updated to reflect this change.
Currently supported flags for asgsh:
-h             -> print command line synopsis, then quits to login shell
-p profileName -> set profile name to start in at the commandline  (e.g.,: % asgsh -p storm042020)
Resolves Issue #244.

Replaced 'set' command with 'define' due to bash keyword conflict.

---

cloud/general/asgs-brew.pl
cloud/general/init-python.sh

Issue #252: To ensure a compatible environment for Python 2.7, versions
for the modules installed via pip were pinned. This was most important
for the netCDF4 module, which removed support for Python 2.7. netCDF4
1.5.2 is also pinned to numpy 1.16.6, so that was also enforced at
the pip level when installing it explicitly. Internal changes to
asgs-brew.pl make it also a little easier to maintain version upgrades.
Even though upstream says there are no more Python 2.7 updates, they
a new minor version was released in March. It's highly likely they
will continue with minor changes like this from time to time to address
security issues and critical bugs, since 2.7 is likely to be heavily
used for many years to come due to it's large installation base.
Resolves #252.

Pinned pip module versions and cleaned up python installation script.

---

asgs_main.sh

Issue 246: Adds awareness to ASGS (asgs_main.sh) of the ADCIRCDIR
environmental variable if set, which is the case with an asgsh
profile when set up as recommended (e.g., using initadcirc and/or
load adcirc <adcirc-installation-name>).
The effective change here is that if ADCIRCDIR is set in the user's
environment when asgs_main.sh is executed, that this value is used
with out having to set it explicity in the ASGS configuratino file.
If ADCIRCDIR is not set or is set to an empty value, asgs_main.sh
will fall back to the traditional behavior of setting it to "null",
thus require ADCIRCDIR to be set explicitly in the configuration
file.
Issue #246 mentions other environmental variables ASGS should track,
but this commit only covers ADCIRCDIR since it provides immediate
value and alleviates …

Make asgs_main.sh aware of ADCIRCDIR if set in environment.

---

asgs_main.sh
doc/monitoring/ASGS_RMQMessaging.md
monitoring/asgs-msgr.sh
monitoring/logging.sh
monitoring/sendTestMessage.sh
platforms.sh

Issue #258: This is a rather aggressive change, but one that is needed
for python stability. It removes the need for "RMQMessaging_Python" to
be set and is not used to run any scripts since all .py scripts should
have the proper shebang and be executable as a result of #256. The loading
of Python via the environment tool "module" that is common on HPCs has
also been removed to further minimize any confusion about which `python`
should be used to execute any scripts.
Resolves #258.

Removed reliance on RMQMessaging_Python envar, purged platforms.sh

---

init-asgs.sh

Issue #308: Was guessing as "smic". Should be "supermic" based on
what's defined in platforms.sh.
Resolves #308.

Fixed init-asgs.sh guess for supermic.

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
cloud/general/init-adcirc.sh

Issue #299: This change bring support for SWAN on par with ADCIRC
and is fully supported in the ADCIRC build profile mechanism in
asgsh. When an ADCIRC profile is loaded, all binaries are now
available via path (e.g., `which unhcat.exe` works, etc).
Issue #312: Discovered and fixed typo when the install directory
was getting added to PATH in asgs-brew.pl. This affected many
binaries being available in PATH - including ncdump, adcirc, adcprep,
padswan, etc.
Resolves #299.
Resolves #312.

Complete SWAN binary support in building and adding to PATH.

---

output/asgsio.f90
output/pullStationTimeSeries.f90
output/resultScope.f90
output/station_transpose.pl

Fixed resultScope.f90 bugs so it can subset ascii fulldomain files to ascii subdomain files; fixed bugs in station_transpose.pl so that it outputs trig and compass directions correctly for current and wind; enable station_transpose.pl to read a dry mask file, aka a water surface elevation fort.61 file, to fill in -99999 for the velocity in dry nodes instead of using whatever is coming from the fort.62 file; added feature to station_transpose.pl so that it would label the column headers in the output according to the raw station number provided in the fort.61. resolves #318 #321 #322 #323 #324

fixes and improvements utilities used to subset results and interpolate at stations 

---

cloud/general/DOT-asgs-brew.sh

Issue 345: The alias approach worked fine except when passing arguments
to one of the 3 disabled utlities. The use of a bash function alls much
more control over how the utilities (now bash functions) are handled.
Resolves #345.

Converted screen, tmux, and asgsh aliases to bash functions.

---

output/asgsConvertR3ToNETCDF.pl
output/opendap_post.sh
output/r3_post.sh
platforms.sh

With the addition of an ssh config under the control of the operator,
the scripts need only to reference the Host alias as defined in
$HOME/.ssh/config. Under each stanza, any of the existing parameters
may be changed (Username, Port, etc) as well as any ssh or scp
options. Since rsync uses ssh by default, it would automatically
derive host specific settings by virtue of using the Host alias as
the reference to the remote server.
This change separates the concerns of ASGS from managing ssh usernames,
hosts, private keys, and "-o" options to focusing on using ssh connections
on a higher level for interacting with remote servers.
The change also allows operators to draw from the same basic ssh config
file, requiring them to only ensure that their respective usernames and
paths to private …

Making ASGS aware of $HOME/.ssh/config for ssh-based connections.

---

get_atcf.pl
nhc_advisory_bot.pl

Issue #381: Made get_atcf.pl more robust in conjuction with many more
changes in the NHC replay scripts. Also detects "replay" server for FTP
and RSS and when detected will use "http" rather than "https". The default
for all over URLs (including the official NHC URLs) will use "https".
Extracting out the text advisory was also made more robust (end of text
advisory detection).
nhc_advisory_bot.pl was also made more robust against the difference
it data/time stamp that changed after 2005. This is so we can run
"nowified" RITA forecasts (and others from 2005 and before).
Resolves #381.

Made NHC advisory detection and parsing more robust.

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
cloud/general/init-adcirc.sh

Issue #391 - Adding support for building v55 of ADCIRC and
updating support for the "load adcirc" command (which updates
$PATH, etc based on where the binaries are expected to be upon
successful compilation)
NOTE: This commit doesn't represent an exhaustive validation process
for use of v55 in ASGS operationally. But this commit is a
precondition for such a validation.

Added support build and "profile" for ADCIRC v55release.

---

NAMtoOWIRamp.pl
archive/enstorm_pedir_removal.sh
config/2021/asgs_config_Shinnecock_nam_jgf.sh
get_nam.pl
util/input/meteorology/get_inv_debug.pl

Resolves #406 to download only the portion (U, V, P) of the grib2 files that are actually needed to provide meteorological forcing. Reduces the disk space usage from 32MB per forecast file (with 28 forecast files needed per NAM forecast) to ~600kB per file.

added partial grib downloading

---

asgs_main.sh

Issue 512: A recent change adding the ability to affect some asgs_main.sh
variables using the interactive environment introduced an error in a shell
assignment that was missing the actual assignment operator (equal sign).
Resolves #512.

Fixed missing assignment introduced in Issue #504.

---

asgs_main.sh

Also fixed QUEUENAME setting to workq for parallel jobs requesting more than 48 cores on QBC. Resolves #516

fixed empty cpurequest property

---

cloud/general/init-adcirc.sh
input/machines/hatteras/hatteras.adcprep.template.slurm
input/machines/hatteras/hatteras.template.slurm
output/cera_contour/cera_contour_multiprog.slurm
qscript.template
qscript.template-test

Issue 538: Changes ensure clarity or that $? is used/captured immediately
after the command of concern.
Resolves #538.

Audited placement of the use/capture of $? (exit code).

---

patches/ADCIRC/v55release-swan-gfortran-10/01-v55release-qbc.patch
patches/ADCIRC/v55release-swan-gfortran/01-v55release-qbc.patch
patches/ADCIRC/v55release/01-v55release-qbc.patch

Issue 548: Manually fixed 3 patches for v55release, all the same;
they were misplacing an 'endif', and only caused issues when building
v55release-* on supermic due to being enclosed in the queenbeeC
section.
Resolves #548.

Fixed patches for v55release that were misplacing an 'endif'.

---

output/opendap_post.sh

Issue 568: If posting to OpenDAP and $SCENARIO is a 'nowcast' or
'hindcast', add it to the subject line.
Resolves #568.

Modify OpenDAP notification email if 'nowcast' or 'hindcast'.

---

output/cpra_postproc/old/tools/Build_Tools.sh
patches/ADCIRC/v53release-issue-549/05-issue-550.patch
patches/ADCIRC/v55release-issue-549/04-issue-550.patch

Note, @jasonfleming, these patches are applied to the following ADCIRC patch sets:
* v53release-issue-549
* v55release-issue-549
I figured we could batch them into this, since we're using these to test the supermic fixes. Once
we finally get it licked, I can roll the accumulated patches into the patch sets for the other respective
versions of adcirc

removing "-assume buffered_io"

---

asgs_main.sh
config/2021/asgs_config_PRVI15_nam_jgf.sh
config/2021/asgs_config_SABv20a_nam_jgf.sh
monitoring/asgs-msgr.sh

RMQ init moved from `asgs_main.sh->variables_init()` to `monitoring/asgs-msgr.sh` to resolve an issue where these variables were not getting set because their initial default values were set only if messaging was enabled, and this was performed before the config file was read to see if the Operator had enabled the messaging. Resolves #611

Moved RMQ variable initialization 

---

asgs_main.sh
platforms.sh

to take care of picking whether not to submit job to a reservation depending on platform and number of CPUs requested. Resolves #632

Added HPC_Reservation_Hint() function 

---

asgs_main.sh

Issue #635: Added the ability to define the get ATCF script via
configuration file using $GET_ATCF_SCRIPT. This is so that the
script that monitors and retrieves the NHC forecasts and best
track data can be easily swapped by setting this variable in a
configuratin file. This is mainly a tool for developing new
get ATCF script, but there might be other uses as well.
Resolves #635.

Made the get ATCF script relocatable, defaults to get_atcf.pl

---

bin/nhc-recorder

Issue #641: Script runs for a long time, monitors the NHC set of currently
active storms, then saves the files whenever a new storm and new advisory
is issued.
Resolves #641.

Adding NHC advisory recorder daemon.

---

PERL-MODULES

Issue #648: Added DBD::SQLite Perl module to default ASGS
installation.
Resolves #648.
(been wanting to do this for a while)

Adding DBD::SQLite to ./PERL-MODULES.

---

output/opendap_post.sh

Issue #646: Adding write-ahead logging (WAL) to $SYSLOG whenever
interacting with at THREDDS (TDS) host via `ssh` or `scp`.
Resolves #646.

Added $SYSLOG entry before an attempted ssh or scp of a TDS host.

---

monitoring/scenarioStatus.awk
monitoring/timestamp.awk

Issue 661: Uses external call to `date` with "getline" capture of output
in awk to capture formatted date. Improves portability of script.
Resolves #661.

Replace unsupported strftime with external `date` call in awk script.

---

cloud/general/DOT-asgs-brew.sh
cloud/general/init-jq.sh

Issue 692: Extended asgsh's 'build' command to support 'jq'; this
commit is also a demonstration of a path forward towards offering
optional things that don't necessarily need to be added at ASGS
build time. In the future, most new software requests should be
available via what will become a poor man's "package manager".
Comands supported by 'build':
build adcirc             # invokes ADCIRC patchset wizard
build jq [clean|rebuild] # standard approach moving ahead
build avail              # (lists available things to build)
Resolves #692.

Added 'jq' as an option post-ASGS-install build step via asgsh.

---

output/opendap_post.sh

Issue 709: Just added a simple check to make sure file exists.
Resolves #709.

Check for run.properties before cat/rm:

---

cloud/general/init-python.sh

Issue 724: Downgraded netCDF4 python module to 1.1.7.1 because
this is the newest version of the module that requires a supported
dependency on numpy.
Part of #724.

Downgraded python netCDF4

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
cloud/general/init-python37.sh

Issue 727: Python 3.7.10 may now be installed into the ASGS Shell
Environment with the command, `build python3`. It will not conflict
with python (2.7.18). Python 2 will be deprecated before the coming
hurricane season. Also, moving forward python will not be installed
automatically unless it's deemed necessary.
Note: No non-core modules are installed, but `pip3` is installed. If
there are python3 modules that should be included by default, they
will be added to this script when identified.
Resolves #727.

Adding optional build support for minimal python 3.7.

---

cloud/general/init-image-magick.sh

Issue 721: We were not able to reproduce the issue described in
the problem report (#721), but took the opportunity to updatre
to the latest version of Image-Magick, currently 7.1.0-22.
Relates to #721.

Updated Image-Magick from 7.1.0-9 to 7.1.0-22.

---

qscript.pl

Issue 733: updated qscript.pl to inject the propery email address/
property into the queue script. Issue found while debugging issue
on QBC when running partmesh phase. May be related to bblanton's
issue on ht4, #723 (maybe, need to confirm).
Resolves #733.

Queue script was getting illegal value for failed email.

---

get_atcf.pl

Issue 741: made script more robust by ensuring that a single digit
[0-9] is passed into the script is more properly formed in order to
generate the best track naming scheme, e.g., "balMMYYYYY.dat".
Resolves #741.

Added zero padding to --storm if a single digit is passed

---

cloud/general/DOT-asgs-brew.sh

Issue 773:
Issue 774:
`clone profile` and `rebuild profile` both offer conveniences for
creating new profiles off of existing ones or recreating profiles
from config files that might have been lost in a reinstall or other
event. Both had some annoying issues dealing with where to place the
new config file and what profile to use as a "base" profile.
Both commands, particularly `clone profile`, are very helpful during
operational times, testing, and training.
Resolves #773.
Resolves #774.

Fixed file path issues with `clone profile` and `rebuild profile`.

---

output/opendap_post.sh
output/opendap_post2.sh

Issue 685: OPENDAPNOTIFY was getting derived from run.properties
once set in the initial run via the opendap_post.sh script(s). This
change removes this propagation via run.properties and allows it
to be changed at run time during the configuration file, which is
preferred.
Resolves #685.

Allow OPENDAPNOTIFY to be updated in config during runtime.

---

monitoring/logging.sh

Resolves #51 ... This is a change in behavior ... previously the ASGS log file `$SYSLOG` was simply dropped in whatever  `$PWD` was set to when `asgs_main.sh` was executed, which was suboptimal, with log files cluttering up my `$HOME`, `$SCRIPTDIR` etc. Now, the default directory for the ASGS log file `$SYSLOG` is set to `$WORK/log` upon startup (creating that directory if necessary). Operators can change $SYSLOG in their ASGS config files if they want to.

Changed default ASGS log dir to $WORK/log

---

get_atcf.pl

Issue 796: StormReplay.com now supports https, so there was no need
to restrict https only to NOAA NHC assets. This change adds a flag
that maybe set when the RSS WWW site needs to use 'http' over 'https'.
Resolves #796.

Added --insecure flag that could be useful for storm testing.

---

cloud/general/asgs-brew.pl
cloud/general/init-hdf5.sh
cloud/general/init-netcdf4.sh

Issue 713: Updating the version of HDF5 and netCDF4, including
the disabling of the HDF5 locking that was introduced after
1.8.12 - which is incidentally the last "working" version of
netCDF on some platforms, in particular LSU's supermic.
Resolves #713.

Updating hdf5 and netCDF4, testing LOCK disable.

---

asgs_main.sh

Issue 827: This change conditions $STORM setting by zero padding
single numbers set in a configuration file; this is a common mistake
that happens during operations, and zero padding is required for
scripts used through the operation forecast runs. It is also required
for properly constructing the full storm designations issued by
the NHC.
Resolves #827.

Ensure STORM is zero-padded for single number storms.

---

output/opendap_post2.sh

Issue 919: During the refactor of opendap_post2.sh, I missed
the email comms tracer, "sendNotification" - which is meant to
act as signal for the script to send an email to the addresses
specified in the configuration file. This was getting removed bec
it isn't meant to be an actual file on the filesystem.
If detected "sendNotification" is added as the last item in the
list of files, so that the message is sent out after all of the
files have been processed. This may provide an opportunity in
the future to have more robust checks and messaging.
Resolves #919.

Adding "sendNotification" file tracer back opendap_post2.sh.

---

cloud/general/asgs-brew.pl
cloud/general/init-pigz.sh

Issue-935: pigz is a parallel verison of gzip that can also produce
zip files. This commit adds it to our toolbox that is installed from
the start.
Resolves #935.

Added pigz, unpigz to set of installed utilities.

---

output/opendap_post2.sh
variables_init.sh
writeProperties.sh

Issue 931: Defining OPENDAPADDROOT in an ASGS configuration file will
cause an additional directory to be prepended to the data path
created and used as the upload target, in output/opendap_post2.sh.
For example, adding the following to the ASGS config fle,
```
OPENDAPADDROOT=replay-test
```
Will ultimately make the files accessible in a url that is rooted
at 'replay-test', e.g.,
```
http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/replay-test/2022/al05/11/TX2008/ls6.tacc.utexas.edu/TX2008-replay-ls6/nhcConsensus/catalog.html
^^^^^^^^^^^^
```
If not set, the URL would normally look as follows,
```
http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/2022/al05/11/TX2008/ls6.tacc.utexas.edu/TX2008-replay-ls6/nhcConsensus/catalog.html
^^^^^^^^^^^^
```
Resolves #931.

Added way to prepend a directory to the OpenDAP path formation.

---

bin/fetch
cloud/general/DOT-asgs-brew.sh

Issue 737: 'fetch' command allows for the easy "getting" (via git checkout
or some other means) of eternal ASGS resources.
Supports:
asgs-configs
asgs.wiki
cera-asgs
storm-archive
adcirc-testsuite
Resolves #737.

Added "fetch" command.

---

asgs_main.sh

resolves #8
The `fort.88` file was used to make sure the nodes on a river influx boundary are wet (otherwise there will be no flow there). This file was supported by ADCIRC v49 and v50, but in v51+ this same capability is provided via nodal attribute. As a result, the requirement for (and support for) a `fort.88` file in ASGS was removed.

removed requirement for `fort.88` when `VARFLUX != off`

---

bin/init-adcirc.sh

Issue 1038: The changes in #1004 took renamed ADCIRCDIR to ADCIRC_WORK_DIR, but this had effects outside of `bin/init-adcirc.sh` (which does the building and contains the wizard). This should not have been done since `ADCIRCDIR` is used externally, e.g., in `./asgs_main.sh`; not to mention the most obvious place that spawned this case, in `load adcirc`. So rather than changing `ADCIRCDIR` everwhere, it was restored. `ADCIRCDIR` preceeded `bin/init-adcirc.sh`.
Resolves #1038.

Fixing `load adcirc` due to lost of `ADCIRCDIR` (put it back).

---

control_file_gen.pl

Resolves #1054
Also handles station files with empty lines (or lines that consist only of spaces). Successfully tested.

Correctly process empty station files

---

bin/tailf
bin/verify
cloud/general/DOT-asgs-brew.sh
etc/bash-completions/tailf.sh

Issue 1114:
* added `$SCRIPTDIR/mail.log` support to `inspect` and `edit` commands
* addedj `$HOME/.asgsh_profile` support to `inspect` and `edit` commands
* added `$HOME/asgs-global.conf` support to `inspect` and `edit` commands
* added an interactive verify sendmail command
* added `mail.log` support as `tailf mail-log`, update bash completion for `tailf`
Resolves #1114.
Resolves #1116 (PR).

Added better support for troubleshooting email sending.

---

asgs_main.sh

Issue 1130:
The old line evaluated to a syntax error when $(checkTimeLimit "$startTime" "$WALLTIME") is empty, at:
if [[ $(checkTimeLimit "$startTime" "$WALLTIME") -eq 1 ]]; then
Effectively evalued to this, which is a syntax error:
if [[ -eq 1 ]]; then
This change doesn't address why the valuation occurs, which would be more of a root issue; however the situation is now robustly detected and reported via the logging function, "warn".
Resolves #1130.

Made call to "checkTimeLimit" in asgs_main.sh more robust.

---

platforms.sh

Issue 1185: LSU HPC now requires the 'single' queue to be used when using single compute node up to the full 64 processors.
Resolves #1185.

Added a queue hint for mike III when using up to 1 full node.

---

cloud/general/DOT-asgs-brew.sh

Issue 1196: Added a sed command to ensure that any filename made for use as STATEFILE from INSTANCENAME will not contain invalid characters.
Resolves #1196.

Ensure STATEFILE file name generated from INSTANCENAME is valid

---

platforms.sh

Issue 1019: If ASGS_LOCAL_DIR is defined, ./platforms.sh will look for a named ssh server in $ASGS_LOCAL_DIR/ssh-servers if the server is not defined in ./platforms.sh AND it's not an officially supported server in $SCRIPTDIR/ssh-servers - if $ASGS_LOCAL_DIR is defined.
Resolves #1019.

Adding support for locally defined remote servers.

---

bin/init-adcirc.sh

Issue 1250: cmplrflags.mk contains a check for DEBUG already that has the proper flags to allow back traces for intel and gfortran.
Resolves #1250.

Added an option to expose the DEBUG option present in cmplrflags.mk.

---

cloud/general/asgs-brew.pl
cloud/general/init-wgrib2.sh
makefile

Issue 1278: The asgs-brew.pl step that was building wgrib2 was no longer calling the correct makefile. Now it is. The wrapper script added to support building the "wgrib2" step is not nearly as complex as other ones in ASGS, but this commit adds some self cleaning.
Resolves #1278.

Fixed a regression introduced in the stampede3 port

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl
platforms/debian/init.sh

Issue 1296: Windows paths were causing start up issues, and it was discovered that the environmental variables were not being quoted. Additionally, it was discovered and fixed that the variable, "ASGS_BREW_FLAGS", was being quoted too early in the process. This was adjusted to be treated like the others.
In addition to this, the default "$WORK" and "$SCRATCH" directories for "debian" were adjusted so that they wer under $HOME, and not a root level directory that would show unnecessary warnings for non-privileged users.
Resolves #1296.

Added quotes around exported variables in profile for Windows paths.

---

cloud/general/init-gnu-units.sh

Issue 1327: The base URL for downloading this package was changed to be a mirror-selector URL, which will find the best mirror to use for downloading this tarball,
https://ftpmirror.gnu.org/
The version of "units" was also updated from 2.21 -> 2.23.
Resolves #1327.

Updated GNU units from 2.21 to 2.23, changed upstream fetch URL.

---

monitoring/captureJobID.sh
platforms.sh

Resolves #1334. Lots of unrelated changes on SuperMIC were also encountered, including Intel compiler upgrade from 2019 to 2021 version. Switching the queueing system on an existing HPC machine required very little change in ASGS. In any case, all Operators will have to rebuild from scratch due to the new library versions installed in the underlying OS. 
After our existing ASGS instance has successfully completed a few cycles, I will take this PR out of draft.

Fixes to support new SuperMIC including switch from PBS to SLURM

---

bin/get_gfs_status.pl
bin/get_nam_status.pl

Issue 1373: This change uses HTTP over FTP for getting lists of files and directories, something needed on TACC's Lonestar6 for some reason.
Resolves #1373.

Replaced Net::FTP with HTTP::Tiny based "ls".

---

bin/fetch
cloud/general/asgs-brew.pl

Issue 1364: Added our fork of Nate's Perl repo to the `fetch` command, use `fetch ourperl`. Updated default PATHs in asgs-brew to include the directories in git/ourPerl and git/asgs-mon; it should be okay that they are fixed like that, it's how all the others were added.
Resolves #1364.

Added ourPerl as "ourperl" to `fetch`, added to default PATHs

---

bin/build
bin/fetch
cloud/general/DOT-asgs-brew.sh
cloud/general/init-jq.sh

Issue 1379:
Issue 1380:
* update 'jq' from 1.6 -> 1.7.1
* moved 'build' to bin/build
* created bin/push to more easily push changes to some bin/fetch'd repos
- `git/asgs-mon` (`fetch asgs-mon` also installs `jq` via `bin/build`)
- `git/asgs-configs`
- `git/docs`
* added the following aliases and short cuts for jumping in and out of config dirs
- `aconfigs` # cd in this year's directory in git/asgs-configs
- `amond`    # cd into asgs-mon's directory
- `amonv`    # run 'asgs-mon -v'
- `cera`     # cd into cera-asgs-environment's directory
- `cerad`    # cd into cera-asgs-environment's daily configs directory
- `docsd`    # cd into asgs.wiki's directory
- `gc`       # cd to the directory containing ASGS_CONFIG if set

Made some operator UX improvements, around configs and asgs-mon.

---

cloud/general/DOT-asgs-brew.sh
cloud/general/asgs-brew.pl

Issue 1379: minor thing I noticed when doing, `which asgs-mon`; adjusted "asmv" alias to use fact asgs-mon is in PATH now.
Related to #1379

Removed trailing '/' in asgs-mon's PATH entry in asgs-brew

---

asgs_main.sh

Issue with caller capturing value of checkTimeLimit bash function

---

platforms/stampede3/init.sh

Issue-1393: Stampede3 has proven to be very fast and reliable during the last couple of hurricanes, notably Hurricane Helene, while using the "spr" queue, which has access to the compute nodes that have 112 PPN.
Resolves #1393.

Updating default Stampede3 specs to match operational use

---

bin/get_gfs_status.pl

Issue 1409: It seems the directory listing HTML changed, and this caused the regexp extracting the GFS directory names to capture HTML elements, thus making the names always invalid.
Resolves #1409.
Resolves #1410 (PR).

Made regexp extracting GFS directy names more robust.

---

bin/get_nam_status.pl

Issue 1411: the problem that was present for GFS downloading was present for NAM also (See #1409).
Resolves #1411.
Resolves #1412 (PR).

Fixed regexp used to get NAM files.

---

patches/ADCIRC/v53release/01-cmplrflags-mk.patch
patches/ADCIRC/v55.01-5bc04d6/01-cmplrflags-mk.patch
patches/ADCIRC/v55.02/01-cmplrflags-mk.patch
patches/ADCIRC/v56.0.2/01-cmplrflags-mk.patch

Issue 1413:
Resolves #1413.
Resolves #1414 (PR).

Updated supermic to use mpiifort with the new Intel suite they added

---

bin/guess
init-asgs.sh
platforms.sh

Issue 890: supermic is one of the few remaining "old" platforms defined directly in platforms.sh. It (and another) platform didn't export "QUEUESYS" directly, so this was added. The latest bin/sq works by inspecting QUEUESYS in the environment rather than using bin/guess and a case statement on the platform name. This change also cleaned up some remaining artifacts from old platforms, incl. stampede2 and poseidon.
Resolves #890.

Fixing supermic to work with latest bin/sq via QUEUESYS

---

patches/ADCIRC/v53release/01-cmplrflags-mk.patch
patches/ADCIRC/v55.01-5bc04d6/01-cmplrflags-mk.patch
patches/ADCIRC/v55.02/01-cmplrflags-mk.patch
patches/ADCIRC/v56.0.2/01-cmplrflags-mk.patch
platforms.sh

Issue 1426: now using mpiifort
Resolves #1424.

Updating ADCIRC for building on QBC after their upgrade to Redhat8.

---

platforms/queenbeeD/init.sh

Setting default compiler for QBD to `intel-oneapi`

---

cloud/general/asgs-brew.pl
cloud/general/init-perl-data-language.sh
cloud/general/init-wgrib2.sh
makefile

This is to get wgrib2 to compile properly without `gfortran`. I thought I had fixed this once before, so I went back and looked. It was being forced to compile with gfortran, something I probably did either in a pinch or it was a regression from merging an old branch. In either case, I think I am close to make sure that wgrib2 can compile with compiler "family" that everything else is compiled with, i.e., "gfortran" (GNU compilers,) "intel" (icc, ifort, etc;) or "intel-oneapi" (icx, ifx, etc.).

fix so wgrib2 can compile with chosen compiler

---

cloud/general/asgs-brew.pl
cloud/general/init-perlbrew.sh

Issue 1455:
* test this with all the Perl stuff we use (`verify perl`)
* builds PDL (`build pdl`)
* PDL::NetCDF installs (`cpanm PDL::NetCDF`)
This doesn't fix the `Alien::OpenMP` issue like I hoped, but that fix is happening in the module itself. I did test the fixed version with this `perl` installationm, and it works fine.
Resolves #1455

Updating Perl 5.38.0 -> 5.40.1

---

bin/fetch

Issue 1457: Adding this for easier use and development.
Resolves #1457.
Note: this requires adding no additional Perl modules.
The purpose of this is to make integrating and developing the adcirclive (tools) cli API client more seamless. Same reason this was done for `asgs-mon` and `asgs-lint`.

Added adcirclive-cli repo to `fetch` command.

---

bin/get_gfs_status.pl
bin/get_nam_status.pl

Issue 1479:
* get_nam.pl doesn't appear to need any updates, it is already using the correct URL and path for the "nomads" HTTPS server
* bin/get_gfs.pl was using one of the HTTPS interfaces for the ftp server, so this was updated to use the correct "nomads" server
WIP - need test and vet any other scripts this may affected.

Updating NCEP URLs

---

bin/init-adcirc.sh
patches/ADCIRC/v53release/about.txt
patches/ADCIRC/v56.0.2/about.txt
patches/ADCIRC/v56.0.4/01-cmplrflags-mk.patch
patches/ADCIRC/v56.0.4/02-macros-inc-gfortran.patch
patches/ADCIRC/v56.0.4/03-DEBUG_WARN_ELEV.patch
patches/ADCIRC/v56.0.4/04-thirdparty-swan-platform-pl.patch
patches/ADCIRC/v56.0.4/about.txt
patches/ADCIRC/v56.0.4/info.sh

Issdue 1482:
Resolves #1482.
Testing (via `build adcirc`, `load adcirc`, and `verify adcirc`)

Add v56.0.4 (keep v56.0.2 but add note about deprecation)

---

bin/list

Issue 1503: the directory structure for storing configurations for officially supported meshes changed, but this impacted the `list meshes` command in a way that stopped the number of nodes from being reported. This PR fixes that.
Meshes that are contained in local assests, if set, are handled as they were before using the original method.
Resolves #1503.

Updated handler for `list meshes`
